### ISSUE TITLE
Make Un-Solo All Button More Easily Accessible

### ISSUE THREAD

**Issue by Shoe-Lac3** [OuChiang/armaturePie#1]
Hey OuChiang,

Thanks for the awesome addon. It has really sped up my workflow and now feels indispensable!

One problem I have is that currently the icons are tiny and really difficult to select compared to the rest of the buttons. 
Also being slightly to the right feels a bit arbitrary - putting them in the center might make more sense?
Do you think to something akin to this might be a better arrangement?

![image](https://github.com/user-attachments/assets/ee5d0a1f-61e1-4a15-8df5-36773359eb10)

**Comment by OuChiang** [comment]
Glad you like this addon

It's a good issue but unfortunately I can't center the middle button
It seems that the layout of the menu pie extends from the center to the lower right
And the scale of buttons is be controlled by preference settings

**Comment by Shoe-Lac3** [comment]
An unfortunate limitation indeed. Guess I'll just have to get used to it - not a huge deal. Thanks again!
